- src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJacocoCoverageStep.java
- src/main/java/nl/tudelft/cse1110/andy/utils/ClassUtils.java
- src/test/java/integration/JacocoTest.java
- src/test/java/unit/utils/ClassUtilsTest.java
- src/test/resources/grader/fixtures/Config/CollectionUtilsIsEqualCollectionCoverageConfiguration.java
- src/test/resources/grader/fixtures/Library/CollectionUtilsIsEqualCollectionLibrary.java
- src/test/resources/grader/fixtures/Solution/CollectionUtilsIsEqualCollectionFullCoverage.java
Jacoco was crashing in case inner classes were there. This PR basically fixes the name of the .class file.
> Fix bug jacoco nested classes

- src/main/java/nl/tudelft/cse1110/andy/writer/weblab/SubmissionMetaData.java
- src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java
WebLab will not provide student information except anonymized id for aggregate analytics.
> Remove student name

- src/test/java/selenium/AllExerciseTests.java
- src/test/java/selenium/WebLabSeleniumTestBase.java
- src/test/java/selenium/pageobjects/BasePageObject.java
- src/test/java/selenium/pageobjects/WebLabAnswerPage.java
- src/test/java/selenium/pageobjects/WebLabAssignmentListElement.java
- src/test/java/selenium/pageobjects/WebLabAssignmentListPage.java
- src/test/java/selenium/pageobjects/WebLabSubmissionPage.java
Added a Selenium test that runs all exercises and checks whether all spec tests get 100%.
The test performs recursive discovery of exercises on WebLab. It then runs all discovered exercises using the sample solution.
As the exercises are discovered using a JUnit generator and the test itself is a parameterised test, all exercises are treated as a separate instance of the test, so it's easy to see which exercise fails.
Furthermore, I changed the login mechanism, so logging in is only done once instead before every individual test. Also, I switched to using JavaScript to enter the solution code in order to improve test performance.
> Create Selenium test that runs all exercises on WebLab

- src/main/java/nl/tudelft/cse1110/andy/AndyOnWebLab.java
> Read submission metadata from arguments instead of environment variables

- src/main/java/nl/tudelft/cse1110/andy/execution/step/SourceCodeSecurityCheckStep.java
Added some more keywords suggested by @Arraying in order to improve detection of reflection usage
> Add more reflection keywords

- .github/workflows/assignments_test.yml
- scripts/assignments_test.py
This PR adds another test phase where it will run all the exercises in the assignments repository and check if they all get a 100/100 score. Currently, this is failing since the assignments repo contains exercises that do not get a full score.
Closes #57
> Add test integration with the assignments repo

- src/main/java/nl/tudelft/cse1110/andy/execution/security/AndySecurityManager.java
> Fix Selenium exceptions triggering the security manager

- src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/TestMethodsHaveAssertions.java
> Add more JUnit assertions to code check

- src/main/java/nl/tudelft/cse1110/andy/writer/standard/StandardResultWriter.java
> Fix message phrasing

- src/main/java/nl/tudelft/cse1110/andy/grade/GradeValues.java
- src/main/java/nl/tudelft/cse1110/andy/result/ResultBuilder.java
- src/test/java/integration/JacocoTest.java
- src/test/resources/grader/fixtures/Config/ArrayUtilsInGradingModeWithDummyCodeCheck.java
- src/test/resources/grader/fixtures/Solution/DummyTest.java
> Override grade to 0 if coverage is 0 

- .github/scripts/assignments_test.py
- .github/scripts/assignments_test_docker.py
- .github/scripts/assignments_test_maven.py
- .github/workflows/assignments_test.yml
- .github/workflows/assignments_test_docker.yml
- .github/workflows/assignments_test_maven.yml
- .github/workflows/tests.yml
- .github/workflows/weblab-tests.yml
> Run all assignments in Docker in CI

- andy/src/main/java/nl/tudelft/cse1110/andy/writer/weblab/EditorFeedbackRange.java
- andy/src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java
- andy/src/test/java/unit/writer/weblab/WebLabEditorFeedbackJsonTestAssertions.java
> Update editor feedback

- andy/src/test/java/integration/SeleniumTest.java
I disabled it by mistake, as I was working without internet. I opened up a ticket to make this test work in offline mode as well.
> R4 enable selenium test

- README.md
- andy/src/main/java/nl/tudelft/cse1110/andy/AndyLauncher.java
- assignments/README.md
Simplify the `AndyLauncher` so it gets easier to run Andy on a random student solution.
> improve the AndyLauncher

- .github/workflows/assignments_test_docker.yml
- weblab-docker/Dockerfile
- weblab-docker/Makefile
- weblab-docker/Makefile.inc
Added a new make target `build-main-branch-github` and set it as the default target.
The old behaviour can still be triggered using `make build`.
> Build Docker image from GitHub

- andy/src/main/java/nl/tudelft/cse1110/andy/execution/metatest/library/LibraryMetaTest.java
> Remove unnecessary check

- andy/src/main/java/nl/tudelft/cse1110/andy/config/SecureExamRunConfiguration.java
> Exammode configuration skipJacoco / skipPitest

- andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/GetRunConfigurationStep.java
- andy/src/main/java/nl/tudelft/cse1110/andy/result/ResultBuilder.java
- andy/src/main/java/nl/tudelft/cse1110/andy/utils/ClassUtils.java
- andy/src/test/java/integration/JUnitTestsTest.java
- andy/src/test/java/testutils/ResultTestDataBuilder.java
- andy/src/test/java/unit/writer/standard/StandardResultWriterTest.java
- andy/src/test/resources/grader/fixtures/Library/LibraryWithConfigClass.java
Show a proper error instead of throwing a NullPointerException.
Fixes #243
> Fix error if multiple classes contain the substring "Config"

- andy/src/main/java/nl/tudelft/cse1110/andy/utils/ClassUtils.java
- andy/src/test/java/integration/CompilationTest.java
- andy/src/test/resources/grader/fixtures/Solution/ListUtilsPackageDeclaration.java
> Fix error when there is no new line after the package declaration

- andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJUnitTestsStep.java
> Fix jqwik configuration in Pitest
