pom.xml
src/main/java/nl/tudelft/cse1110/andy/AndyOnWebLab.java
src/main/java/nl/tudelft/cse1110/andy/utils/PropertyUtils.java
src/main/java/nl/tudelft/cse1110/andy/writer/standard/StandardResultWriter.java
src/main/java/nl/tudelft/cse1110/andy/writer/standard/VersionInformation.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java
src/main/resources/version.properties
src/test/java/integration/WebLabTest.java
src/test/java/unit/writer/standard/StandardResultTestAssertions.java
src/test/java/unit/writer/standard/StandardResultWriterTest.java
src/test/java/unit/writer/weblab/WebLabResultWriterTest.java

Added the Maven version, latest git commit and build timestamp in the output generated by StandardResultWriter. Added tests for the new behaviour.
This changed the parameters accepted by StandardResultWriter, so a modification in the Mojo is also necessary - https://github.com/cse1110/andy-maven-plugin/pull/4

Add version information

---

src/main/java/nl/tudelft/cse1110/andy/execution/mode/ModeActionSelector.java
src/main/java/nl/tudelft/cse1110/andy/writer/standard/StandardResultWriter.java
src/test/java/unit/writer/standard/StandardResultTestAssertions.java
src/test/java/unit/writer/standard/StandardResultWriterTest.java

Print a suitable explanation to the output when the weblab score is overridden to 0/100 due to the selected mode or action

Print explanation when test score is 0/100

---

src/main/java/nl/tudelft/cse1110/andy/writer/weblab/SubmissionMetaData.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java

A nice-to-have analytics is seeing how many different types have been submitted per an exercise. In order to send this information to the analytics application, I added `Action` to `SubmissionMetaData`.

Add Action to SubmissionMetaData

---

src/main/java/nl/tudelft/cse1110/andy/execution/security/AndySecurityManager.java
src/test/java/integration/SecurityTest.java

Improved the message thrown in the SecurityManager, and removed the line that prints the stacktrace every time a SecurityException is thrown, as it is no longer necessary.

Improve SecurityException message

---

src/main/java/nl/tudelft/cse1110/andy/execution/step/SourceCodeSecurityCheckStep.java

`getClass()` is sometimes used in the `equals` methods of classes in order to compare their type. It can cause false positives, so I think it's best to remove it from the blacklist.

Remove "getClass" from security keyword blacklist as it can cause false positives

---

src/main/java/nl/tudelft/cse1110/andy/Andy.java
src/main/java/nl/tudelft/cse1110/andy/AndyOnWebLab.java
src/main/java/nl/tudelft/cse1110/andy/execution/Context.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/Submission.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/SubmissionMetaData.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java

Read meta data from environment according to [this](https://3.basecamp.com/4338320/buckets/22606949/todos/3837601280#__recording_4361054885).
I do not know how to run Andy in WebLab so I would like someone else to check that the output has correct meta data.

Read meta data from environment

---

src/main/java/nl/tudelft/cse1110/andy/config/RunConfiguration.java
src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJacocoCoverageStep.java
src/main/java/nl/tudelft/cse1110/andy/execution/step/RunPitestStep.java
src/test/java/integration/JacocoTest.java
src/test/java/integration/PitestTest.java
src/test/resources/grader/fixtures/Config/NumberUtilsJacocoSkipped.java
src/test/resources/grader/fixtures/Config/ZagZigPitestSkipped.java

Added two methods in `RunConfiguration` - `skipJacoco()` and `skipPitest()`, which can be overriden in order to disable Pitest and Jacoco in exercises where it doesn't make sense to run them, such as exercises that rely on testing an external process.

Add configuration options to skip Jacoco or Pitest

---

src/main/java/nl/tudelft/cse1110/andy/Andy.java
src/main/java/nl/tudelft/cse1110/andy/writer/weblab/SubmissionMetaData.java

Overload the Andy constructor in order to preserve backward compatibility after the changes introduced in #70 as those changes break the Maven plugin
Fixes #83

Overload constructor

---

src/main/java/nl/tudelft/cse1110/andy/execution/metatest/library/evaluators/StringReplacementEvaluator.java
src/test/java/integration/LibraryMetaTestsTest.java
src/test/resources/grader/fixtures/Config/NumberUtilsAddConfigurationWithMetaTestInternalFailure.java

The check that ensures the code to be replaced is actually present in the library was wrong.

Fix meta test nonexistent replacement check

---

pom.xml

This will update the log4j dependency to avoid a remote code execution attack while grading. This internally replaces log4j with [reload4j](https://reload4j.qos.ch/) which is a drop-in by the guys who make Logback (my logger of choice). reload4j fixes security vulnerabilities on ancient versions of log4j such as ours, while Apache refuses to do so.
My tests were running a little flakey today, but I think that was due to my filesystem being bugged; I hope the pipeline passes.

Update logger dependency and move from log4j to reload4j.

---

.gitignore
README.md

A small change to the README which replaces the word `execute` with `run` in order to avoid  potential confusion of whether the awkward connotation of summarily executing the current director of studies of the CSE bachelor. The change proposed still is relatively vague on what it does. However the potential implementation of the program would, in the worst case, help professor Zaidman with his cardio as opposed to starting an autonomous swarm of murder robots.

Changes the README to uphold the sancity of human life

---

src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/TestMethodsHaveAssertions.java

Added more methods that can be used to write assertions with AssertJ to the `TestMethodsHaveAssertions` code check.
Closes #106

Fix some AssertJ assertions not being recognised by code check

---

src/main/java/nl/tudelft/cse1110/andy/result/UnitTestsResult.java
src/main/java/nl/tudelft/cse1110/andy/writer/standard/StandardResultWriter.java
src/test/java/integration/JUnitTestsTest.java
src/test/java/unit/writer/standard/StandardResultWriterTest.java
src/test/resources/grader/fixtures/Solution/ArrayUtilsIsSortedWithGeneratorMethodError.java

Instead of the "no tests found" message, the exception messages generated by JUnit or the tips from [JUnitUtils#simplifyTestErrorMessage](https://github.com/cse1110/andy/blob/71c986f0b05037696a8d605a1cb3131b079a7222/src/main/java/nl/tudelft/cse1110/andy/utils/JUnitUtils.java#L7) are shown when Andy finds no tests due to a reported test failure.
Fixes #117

Fix "no tests found" message being shown if generator method lookup fails

---

src/main/java/nl/tudelft/cse1110/andy/execution/ExecutionFlow.java
src/main/java/nl/tudelft/cse1110/andy/execution/step/GetRunConfigurationStep.java
src/main/java/nl/tudelft/cse1110/andy/execution/step/InjectModeActionStepsStep.java
src/main/java/nl/tudelft/cse1110/andy/writer/standard/StandardResultWriter.java
src/test/java/integration/GenericFailureWithHintTest.java
src/test/java/integration/GenericFailureWithStandardResultWriterTest.java
src/test/java/integration/IntegrationTestBase.java
src/test/java/unit/writer/standard/StandardResultTestAssertions.java

A hint is now shown if Pitest fails because the student's tests are flaky:
```
Andy v0.29-SNAPSHOT-9b2519a (2022-08-29T23:03:10+0200)
An error occurred while running your tests.
---
It appears that your test suite is flaky. Make sure that your tests do not randomly fail for no reason.
---
Full details:
The failure occurred in RunPitestStep
---
org.pitest.help.PitHelpError: 1 tests did not pass without mutation when calculating line coverage. Mutation testing requires a green suite.
See http://pitest.org for more details.
at org.pitest.coverage.execute.DefaultCoverageGenerator.verifyBuildSuitableForMutationTesting(DefaultCoverageGenerator.java:115)
at org.pitest.coverage.execute.DefaultCoverageGenerator.calculateCoverage(DefaultCoverageGenerator.java:97)
[...]
```
Perhaps there's a similar …

Add hint when Pitest fails due to flaky tests

---

.github/workflows/assignments_test.yml
.github/workflows/assignments_test_maven.yml
.github/workflows/tests.yml
.github/workflows/weblab-tests.yml
pom.xml
src/main/java/nl/tudelft/cse1110/andy/codechecker/engine/CheckScript.java
src/main/java/nl/tudelft/cse1110/andy/execution/step/CompilationStep.java
src/test/java/integration/JUnitTestsTest.java
src/test/java/unit/codechecker/JDTParser.java
src/test/resources/grader/fixtures/Solution/ArrayUtilsIndexOfJqwikWithParameterizedWithRecord.java

Parts of the compilation were done with old Java 9 components. This caused issues when newer syntax is used.
Fixes #116

Fix record classes resulting in an exception

---

scripts/assignments_test.py
src/main/java/nl/tudelft/cse1110/andy/utils/ClassUtils.java
src/test/java/integration/JUnitTestsTest.java
src/test/resources/grader/fixtures/Config/RestaurantsConfiguration.java
src/test/resources/grader/fixtures/Library/LibraryWithBadTestTemplate.java
src/test/resources/grader/fixtures/Library/RestaurantsLibrary.java
src/test/resources/grader/fixtures/Solution/RestaurantsOfficialSolution.java
src/test/resources/grader/fixtures/Solution/SolutionWithBadInheritance.java

Added this test in an attempt to reproduce #114 
The issue with SQL tests is that there is a test template class in the library (which contains SQL-related test setup code). This class is the parent class of the student's actual test class.
This parent class also matched the rules for test class discovery - its name contained the substring `Test`. As Andy does not expect that, it picks an arbitrary class matching that condition, meaning that on each execution either the actual test class or this dummy class containing no test methods will randomly be picked to be run, leading to the observed flakiness.
I fixed that by renaming the template class and adding a check to Andy to throw an exception if multiple matching classes are found, instead of simply picking one to make sure this does not …

Fix issue with test discovery and add a system test for an SQL exercise

---

src/main/java/delft/GeneratedExcludeFromJacoco.java
src/test/java/integration/JacocoTest.java
src/test/resources/grader/fixtures/Config/AutoAssignerConfiguration.java
src/test/resources/grader/fixtures/Library/AutoAssignerLibrary.java
src/test/resources/grader/fixtures/Solution/AutoAssignerOfficialSolution.java

I added the annotation in a new `delft` package inside Andy so that it can directly be used in the library without the need to import it.
Closes #127

Include jacoco coverage annotation by default

---

src/main/java/nl/tudelft/cse1110/andy/execution/step/SourceCodeSecurityCheckStep.java

An issue allowed students to create a custom ClassLoader and load raw bytecode. This code could then circumvent all static and dynamic security checks.

Fix issue allowing circumvention of security checks

---

andy/src/main/java/nl/tudelft/cse1110/andy/writer/weblab/EditorFeedbackRange.java
andy/src/test/java/unit/writer/weblab/WebLabEditorFeedbackJsonTestAssertions.java

In WebLab we decided to change `startLine` and `endLine` to `startLineNumber` and `endLineNumber` in the highlight JSON file. This simple PR changes the need to edit it yourself.

Change name of `startLine` and `endLine` properties in highlight JSON

---

andy/src/main/java/nl/tudelft/cse1110/andy/writer/weblab/EditorFeedbackRange.java
andy/src/main/java/nl/tudelft/cse1110/andy/writer/weblab/WebLabResultWriter.java
andy/src/test/java/unit/writer/weblab/WebLabEditorFeedbackJsonTestAssertions.java

The title says it all, we changed the editor feedback format in WebLab such that the "location" property is now called "file", this PR makes Andy's editor feedback compatible again.

Change "location" property in editor feedback to "file"

---

andy/src/test/java/selenium/AllExerciseTests.java
andy/src/test/java/selenium/ExamAssignmentTests.java
andy/src/test/java/selenium/PracticeAssignmentTests.java
andy/src/test/java/selenium/SecurityExploitTests.java

In MR adds `@Tag` to tests that are more meant to be run in the CI. For example, the WebLab tests that require extra configuration. Tags make it easy for us to exclude them in local (via a simple JUnit configuration).

Tagging tests that are meant to run in CI

---

andy/src/main/java/nl/tudelft/cse1110/andy/execution/Context.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/mode/Action.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/mode/ModeActionSelector.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/CollectCoverageInformationStep.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/InstrumentCodeForCoverageStep.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJUnitTestsStep.java
andy/src/test/java/integration/JacocoTest.java
andy/src/test/java/integration/ModesAndActionsTest.java
andy/src/test/java/unit/execution/mode/ModeActionSelectorTest.java

Currently, Andy re-runs the tests if we decide to collect coverage. With this MR, the engine follows the steps:
* Instruments all the code
* Runs JUnit
* Collects the data
This means we run the tests only once. Given that instrumenting the code is easy, we do this now also when "only running tests". We leave "coverage" now to the expensive coverage that's mutation testing.
This MR tackles issue #176

Coverage doesn't require the tests to run again

---

andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJUnitTestsStep.java

This MR changes the following configs:
* jqwik.tries.default: Instead of running 1000 data points, we just run 100. Enough for teaching purposes.
* jqwik.shrinking.default: If it finds a bug, no need for shrinking, we want to return as early as possible.

Improve jqwik configs to speed up execution

---

.github/workflows/assignments_test.yml
.github/workflows/assignments_test_docker.yml
.github/workflows/tests_docker.yml
.github/workflows/weblab-tests.yml

Disable CI workflows that need re-work

---

assignments/property-based-testing/unique/src/main/java/delft/MathArraysPBT.java

This MR renames `MathArrays` to `MathArraysPBT` to avoid name collision.

R01: Rename file to avoid collision

---

andy-aws-lambda/src/main/java/nl/tudelft/cse1110/andy/aws/AWSResult.java
andy-aws-lambda/src/main/java/nl/tudelft/cse1110/andy/aws/AndyOnAWSLambda.java
andy-maven-plugin/src/main/java/io/github/cse1110/andy/AndyMojo.java
andy/src/main/java/nl/tudelft/cse1110/andy/Andy.java
andy/src/main/java/nl/tudelft/cse1110/andy/AndyLauncher.java
andy/src/main/java/nl/tudelft/cse1110/andy/AndyOnWebLab.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/Context.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/ExecutionFlow.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/metatest/externalprocess/ExternalProcessMetaTest.java
andy/src/main/java/nl/tudelft/cse1110/andy/execution/metatest/library/LibraryMetaTest.java
andy/src/test/java/integration/IntegrationTestBase.java
andy/src/test/java/integration/InvalidConfigurationTest.java
andy/src/test/java/integration/SeleniumTest.java
andy/src/test/java/integration/WebLabTest.java

Andy's logic was quite coupled with the writer. In this MR, I extract the Writer to outside the main Andy execution. Andy returns a `Result` and each main (weblab, launcher, aws) does whatever it wants with the result.

R3 Separate Andy from the writer

---

weblab-docker/Dockerfile

Docker was caching the `git clone` command, causing it to use an old branch version from cache. Fixed it by forcibly writing a file which changes every time a new commit is pushed (from the GitHub API), which should block the caching mechanism, as the image state would be different.

Fix Docker using an old branch version from cache

---

andy/src/test/java/integration/JacocoTest.java
andy/src/test/java/integration/assignments/AllAssignmentsTest.java
andy/src/test/java/unit/execution/metatest/LibraryMetaTestTest.java
andy/src/test/java/unit/utils/CodeSnippetUtilsTest.java

Solves #207
I decided that simple naming scheme of index and name of parametrized test is good solution. It requires single line of code and if test fails it is easy to run it locally in IntelliJ and identify the problem.
Here are new outputs. I have changed the ones with long lines or containing line breaks.

Reduce verbose test sysouts

---

andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJUnitTestsStep.java
andy/src/test/java/integration/JUnitTestsTest.java
andy/src/test/resources/grader/fixtures/Solution/ArrayUtilsIndexOfAssumptionJqwikError.java
andy/src/test/resources/grader/fixtures/Solution/ArrayUtilsIndexOfMultipleJqwikErrors.java

This PR adds another configuration step inside the jqwik config inside [RunJUnitTestsStep](https://github.com/SERG-Delft/andy/blob/main/andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/RunJUnitTestsStep.java) that sets the maximum discard ratio to 2.
Additionally, this PR adds a new Solution fixture to check for discarding of a "correct" solution that uses Assume to filter out disproportionately big number of entries and changes the `testMultiplePropertyTestsFailing` method and relating fixture to test the scenario if a correct property with bad assumption filtering fails in the context of other failing property-based tests.
Closes #246

Add config setting for max discard ration to 2

---

.github/scripts/assignments_test_docker.py

The aim of this MR is to add more random assignment tests (4) in docker, as per discussed in #236 
Closes #251

Add more assignment tests in docker 

---

andy/src/main/java/nl/tudelft/cse1110/andy/execution/step/ReplaceClassloaderStep.java
andy/src/main/java/org/mockito/configuration/MockitoConfiguration.java
andy/src/test/java/integration/LibraryMetaTestsTest.java
andy/src/test/resources/grader/fixtures/Config/MockingAssignmentWithCustomExceptionConfiguration.java
andy/src/test/resources/grader/fixtures/Library/MockingAssignmentWithCustomExceptionLibrary.java
andy/src/test/resources/grader/fixtures/Solution/MockingAssignmentWithCustomExceptionWrongWithoutAssertions.java

In meta tests, we dynamically reload classes. This causes casting issues when Objenesis caches an instantiator for a class that is later replaced.

Configure Mockito to disable the Objenesis class cache

---

andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/MockitoWhen.java
andy/src/test/resources/codechecker/fixtures/MockitoWhenCalls.java

The current implementation was checking for Mockito do-syntax in the form `doReturn(something).when(repository.find(1))`, which is invalid syntax. It should instead be `doReturn(something).when(repository).find(1)`.

Fix Mockito do-syntax

---

.github/workflows/tests.yml
andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/MethodCalledAnywhere.java
andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/MethodCalledInTestMethod.java
andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/TestMethodsHaveAssertions.java
andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/WithinAnnotatedMethod.java
andy/src/test/java/unit/codechecker/checks/MethodCalledAnywhereTest.java
andy/src/test/java/unit/codechecker/checks/MethodCalledInTestMethodTest.java
andy/src/test/resources/codechecker/fixtures/MethodCalled.java
andy/src/test/resources/codechecker/fixtures/StackOverflowTestWithAnonymousClass.java

MethodCalledInTestMethod currently only supports finding calls to methods with a specific name. In cases of methods like `of`, there could be many different classes that have this method (like `Arbitraries.of` and `List.of`), and it becomes impossible to exactly match the method calls that we want.
This pull request adds a way to match on the expression (the left hand side of the dot, e.g. `Arbitraries`). 
I am aware of the fact that the value of this is limited: if we wanted to forbid writing `Arbitraries.of`, one could easily write something like `(new Arbitraries()).of` (if there were such a public constructor) and therefore bypass the check.
I attempted to make this more robust by requesting the type bindings for the expression (and then match on that), but this does not always work. …

Add a constructor to MethodCalledInTestMethod to support matching a specific expression

---

andy/src/main/java/nl/tudelft/cse1110/andy/result/MetaTestsResult.java
andy/src/test/java/integration/CodeChecksTest.java
andy/src/test/java/integration/LibraryMetaTestsTest.java
andy/src/test/resources/grader/fixtures/Config/NumberUtilsAddConfigurationWithZeroWeight.java
andy/src/test/resources/grader/fixtures/Config/SoftWhereConfigWithCodeChecksZeroWeight.java

Removed the incorrect precondition which would cause Andy to fail if all meta tests have a weight of 0.
Added integration tests for zero-weight meta tests and code checks.
Fixes #275

Remove incorrect meta test precondition

---

andy/src/main/java/nl/tudelft/cse1110/andy/codechecker/checks/MockClass.java
andy/src/test/java/unit/codechecker/checks/MockClassTest.java
andy/src/test/resources/codechecker/fixtures/ManyMocks.java

A student wrote this:
```java
class SecurityScannerTest {
private SecurityOfficer securityOfficer;
// ...
private SecurityScanner scanner;
@BeforeEach
public void setUp() {
securityOfficer = mock();
// ...
}
}
```
This is now valid Mockito syntax, so we want to make sure that we detect such a way to create a mock of a class (in this case the `SecurityOfficer` class).

Add support for parameterless mock() invocations
